# Generated by Django 4.2.3 on 2023-07-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='acceptance',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=20, null=True),
        ),
    ]
